/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./components/Grid/ActionsMenu.vue')['default']
    AppDashboardLayout: typeof import('./layouts/AppDashboardLayout.vue')['default']
    Campaigns: typeof import('./components/Icons/Campaigns.vue')['default']
    DataBlock: typeof import('./components/Grid/DataBlock.vue')['default']
    Details: typeof import('./components/Grid/Details.vue')['default']
    GridHeader: typeof import('./components/Grid/GridHeader.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/Test/HelloWorld.vue')['default']
    Inbox: typeof import('./components/Icons/Inbox.vue')['default']
    Indicator: typeof import('./components/Icons/Indicator.vue')['default']
    Leads: typeof import('./components/Icons/Leads.vue')['default']
    Link: typeof import('./components/Icons/Link.vue')['default']
    MenuItem: typeof import('./components/Menu/MenuItem.vue')['default']
    Nav: typeof import('./components/Navbar/Nav.vue')['default']
    NavItem: typeof import('./components/Navbar/NavItem.vue')['default']
    ProgressBar: typeof import('./components/Grid/ProgressBar.vue')['default']
    Report: typeof import('./components/Grid/Report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Table: typeof import('./components/Grid/Table.vue')['default']
  }
}
