export const menu = [
  {
    id: 1,
    title: "All Leads",
    link: "/",
    icon: "leads",
    isActive: false,
  },
  {
    id: 2,
    title: "Master Inbox",
    link: "/",
    icon: "inbox",
    isActive: false,
  },
  {
    id: 3,
    title: "Email Campaigns",
    link: "/",
    icon: "campaigns",
    isActive: true,
  },
];
export const nav = [
  {
    id: 1,
    title: "Alll Campaigns",
    count: 24,
    isActive: true,
  },
];

export const list = [
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 1,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 1,
    statusText: "Sent",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 2,
    title: "SW Zero Personalisation 2",
    date: "15 Apr 2023",
    status: 2,
    statusText: "Drafted",
    sequence: 3,
    progress: 30,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 3,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 3,
    statusText: "Stopped",
    sequence: 3,
    progress: 50,
    warning: true,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
  {
    id: 4,
    title: "SW Zero Personalisation 1",
    date: "15 Apr 2023",
    status: 4,
    statusText: "Paused",
    sequence: 3,
    progress: 80,
    warning: false,
    report: [
      {
        title: "sent",
        count: 520,
        type: 1,
      },
      {
        title: "clicked",
        count: 39,
        type: 2,
        percent: 19.6,
      },
      {
        title: "opened",
        count: 202,
        type: 3,
        percent: 19.6,
      },
      {
        title: "replied",
        count: 4,
        type: 4,
        percent: 19.6,
      },
      {
        title: "positive reply",
        count: 0,
        type: 5,
        percent: 19.6,
      },
    ],
  },
];
